<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('countries')->insert([
            [
                'name' => 'España',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Angola',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Estados Unidos',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Italia',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Japón',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Francia',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Reino Unido',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Australia',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('films')->insert([
            [
                'name' => 'Hable con ella',
                'country' => 1,
                'year' => 2002,
                'length' => 112,
                'image' => 'hable_con_ella.jpg',
                'description' => 'Dos hombres desarrollan una extraña amistad mientras cuidan a dos mujeres que están en coma profundo.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ar Condicionado',
                'country' => 2,
                'year' => 2020,
                'length' => 72,
                'image' => 'ar_condicionado.jpg',
                'description' => 'Cuando los aparatos de aire acondicionado comienzan a caer misteriosamente en la ciudad de Luanda, Matacedo y Zezinha tienen la misión de recuperar el aire acondicionado de su jefe.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Taxi Driver',
                'country' => 3,
                'year' => 1976,
                'length' => 113,
                'image' => 'taxi_driver.jpg',
                'description' => 'Un veterano con problemas de salud mental trabaja como taxista en Nueva York, donde su percepción de la decadencia a su alrededor alimenta su deseo de violencia.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Goodfellas',
                'country' => 3,
                'year' => 1990,
                'length' => 148,
                'description' => 'La historia de Henry Hill y su vida en la mafia, abarcando su relación con su esposa Karen Hill y sus socios mafiosos Jimmy Conway y Tommy DeVito en el sindicato del crimen italoamericano.',
                'image' => 'goodfellas.jpg',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'El verdugo',
                'country' => 1,
                'year' => 1963,
                'length' => 90,
                'image' => 'el_verdugo.jpg',
                'description' => 'Un empresario de pompas fúnebres se casa con la hija de un viejo verdugo y debe continuar con la profesión de su suegro tras su jubilación, aunque no le gusta.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Yojimbo',
                'country' => 5,
                'year' => 1961,
                'length' => 110,
                'image' => 'yojimbo.jpg',
                'description' => 'Un astuto samurái ronin llega a un pueblo dividido por dos bandas criminales y decide enfrentar a una contra otra para liberar el pueblo.',       
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Django',
                'country' => 4,
                'year' => 1966,
                'length' => 91,
                'image' => 'django.jpg',
                'description' => 'Un pistolero y una prostituta mestiza se ven envueltos en una amarga disputa entre una banda de racistas sureños y otra de revolucionarios mexicanos.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Retrato de una mujer en llamas',
                'country' => 6,
                'year' => 2019,
                'length' => 120,
                'image' => 'retrato_de_una_mujer_en_llamas.jpg',
                'description' => 'En una isla aislada de Bretaña a finales del siglo XVIII, una pintora se ve obligada a pintar el retrato de boda de una joven',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Carol',
                'country' => 7,
                'year' => 2015,
                'length' => 118,
                'image' => 'carol.jpg',
                'description' => 'Una aspirante a fotógrafa desarrolla una íntima relación con una mujer mayor en la Nueva York de los 50.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'La naranja mecánica',
                'country' => 7,
                'year' => 1971,
                'length' => 137,
                'image' => 'la_naranja_mecanica.jpg',
                'description' => 'En el futuro, el sádico líder de una banda es encarcelado y se ofrece como voluntario para un experimento de reeducación, pero no sale según lo planeado.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Alien',
                'country' => 3,
                'year' => 1979,
                'length' => 116,
                'image' => 'alien.jpg',
                'description' => 'La tripulación de una nave espacial comercial se encuentra con una forma de vida mortal tras investigar una transmisión desconocida.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'As Bestas',
                'country' => 1,
                'year' => 2022,
                'length' => 137,
                'image' => 'as_bestas.jpg',
                'description' => 'Una pareja francesa de mediana edad se muda a un pequeño pueblo español en busca de cercanía con la naturaleza donde su presencia inflama a dos lugareños hasta el punto de una abierta hostilidad y una violencia impactante.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('directors')->insert([
            [
                'name' => 'Pedro Almodóvar',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('25 september 1949')),
                'image' => 'pedro_almodovar.jpg',
                'description' => 'Pedro Almodóvar Caballero es un director, guionista y productor de cine español. Fundó la productora de cine española El Deseo S.A. con su hermano menor Agustín Almodóvar, quien ha producido casi todas las películas de Pedro. Fue elegido Miembro Honorario Extranjero de la Academia Estadounidense de las Artes y las Ciencias en 2001.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Mário "Fradique" Bastos',
                'country' => 2,
                'birthdate' => date('Y-m-d H:i:s', strtotime('1986')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Martin Scorsese',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('17 november 1942')),
                'image' => 'martin_scorsese.jpg',
                'description' => 'Martin Charles Scorsese (nacido el 17 de noviembre de 1942) es un director de cine, productor, guionista y actor estadounidense. Una de las principales figuras de la era del Nuevo Hollywood, es ampliamente considerado como uno de los directores más grandes e influyentes de la historia del cine. El cuerpo de trabajo de Scorsese explora temas como la identidad italoamericana, los conceptos católicos de culpa y redención, la fe, el machismo, el nihilismo, el crimen y el sectarismo.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Luis García Berlanga',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('12 june 1921')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Akira Kurosawa',
                'country' => 5,
                'birthdate' => date('Y-m-d H:i:s', strtotime('23 march 1910')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Sergio Corbucci',
                'country' => 4,
                'birthdate' => date('Y-m-d H:i:s', strtotime('6 december 1926')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Céline Sciamma',
                'country' => 6,
                'birthdate' => date('Y-m-d H:i:s', strtotime('12 november 1980')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Todd Haynes',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('2 january 1961')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Stanley Kubrick',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('26 july 1928')),
                'image' => 'stanley_kubrick.jpg',
                'description' => 'Stanley Kubrick fue un director de cine, guionista, productor y fotógrafo estadounidense nacionalizado británico. Considerado por muchos como uno de los cineastas más influyentes del siglo XX, destacó tanto por su precisión técnica como por la notable estilización y la profunda carga simbólica de sus películas.​',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ridley Scott',
                'country' => 7,
                'birthdate' => date('Y-m-d H:i:s', strtotime('30 november 1937')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Rodrigo Sorogoyen',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('16 september 1981')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('filmographies')->insert([
            [
                'film' => 1,
                'director' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 2,
                'director' => 2,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 3,
                'director' => 3,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 4,
                'director' => 3,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 5,
                'director' => 4,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 6,
                'director' => 5,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 7,
                'director' => 6,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 8,
                'director' => 7,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 9,
                'director' => 8,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 10,
                'director' => 9,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 11,
                'director' => 10,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 12,
                'director' => 11,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('actors')->insert([
            [
                'name' => 'Javier Cámara',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('19 january 1967')),
                'image' => 'javier_camara.jpeg',
                'description' => 'Javier Cámara Rodríguez un actor español. Ha ganado dos premios Goya, y en 2022 fue galardonado con la Medalla de Oro al Mérito en las Bellas Artes que otorga el Ministerio de Cultura de España.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'José Kiteculo',
                'country' => 2,
                'birthdate' => null,
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Robert De Niro',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('17 august 1943')),
                'image' => 'robert_de_niro.jpg',
                'description' => 'Robert Anthony De Niro es un actor y productor estadounidense. Ganador de dos premios Óscar por su actuación en las películas El padrino: Parte II (1974) como un joven Vito Corleone y Toro salvaje (1980) como Jake LaMotta. Es ampliamente conocido por sus papeles de gánster y de personajes conflictivos y turbulentos.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Jodie Foster',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('19 november 1962')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ray Liotta',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('18 december 1954')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Nino Manfredi',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('22 march 1954')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'José Isbert',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('3 march 1886')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Toshirō Mifune',
                'country' => 5,
                'birthdate' => date('Y-m-d H:i:s', strtotime('1 april 1920')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Franco Nero',
                'country' => 4,
                'birthdate' => date('Y-m-d H:i:s', strtotime('23 november 1941')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Noémie Merlant',
                'country' => 6,
                'birthdate' => date('Y-m-d H:i:s', strtotime('27 november 1988')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],        
            [
                'name' => 'Adèle Haenel',
                'country' => 6,
                'birthdate' => date('Y-m-d H:i:s', strtotime('11 february 1989')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Rooney Mara',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('17 april 1985')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Cate Blanchett',
                'country' => 8,
                'birthdate' => date('Y-m-d H:i:s', strtotime('14 may 1969')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Malcolm McDowell',
                'country' => 7,
                'birthdate' => date('Y-m-d H:i:s', strtotime('13 june 1943')),
                'image' => 'malcolm_mcdowell.jpg',
                'description' => 'Malcolm John Taylor, más conocido como Malcolm McDowell, es un actor de televisión y cine británico. A lo largo de una trayectoria de más de cincuenta años, ha interpretado toda clase de papeles como actor de carácter.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Sigourney Weaver',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('8 october 1949')),
                'image' => 'sigourney_weaver.jpg',
                'description' => 'Susan Alexandra Weaver, más conocida como Sigourney Weaver, es una actriz y productora estadounidense de cine, televisión y teatro. Ha sido candidata a los Premios Óscar y a los Premios del Sindicato de Actores.​',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'John Hurt',
                'country' => 7,
                'birthdate' => date('Y-m-d H:i:s', strtotime('22 january 1940')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Denis Ménochet',
                'country' => 6,
                'birthdate' => date('Y-m-d H:i:s', strtotime('18 september 1976')),
                'image' => 'denis_menochet.jpg',
                'description' =>'Denis Ménochet es un actor francés, conocido sobre todo por sus participaciones en películas como Hannibal, el origen del mal, Inglourious Basterds, Robin Hood, Forces spéciales y As bestas',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Marina Foïs',
                'country' => 6,
                'birthdate' => date('Y-m-d H:i:s', strtotime('21 January 1970')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Luis Zahera',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('23 may 1966')),
                'image' => 'luis_zahera',
                'description' => 'José Luis de Castro Zahera, más conocido como Luis Zahera, es un actor español, ganador de un Goya en 2019 y en 2023 por su interpretación en El reino y As bestas, respectivamente',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],                                                                                                                             
        ]);
        
        DB::table('casts')->insert([
            [
                'film' => 1,
                'actor' => 1,
                'character' => 'Benigno Martín',                           
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 2,
                'actor' => 2,
                'character' => 'Matacedo',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 3,
                'actor' => 3,
                'character' => 'Travis Bickle',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 3,
                'actor' => 4,
                'character' => 'Iris Steensma',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 4,
                'actor' => 5,
                'character' => 'Henry Hill',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 4,
                'actor' => 3,
                'character' => 'James Conway',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 5,
                'actor' => 6,
                'character' => 'Jose Luis Rodríguez, el enterrador',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 5,
                'actor' => 7,
                'character' => 'Amadeo, el verdugo',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 6,
                'actor' => 8,
                'character' => 'Sanjuro Kuwabatake, El samurái',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 7,
                'actor' => 9,
                'character' => 'Django',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 8,
                'actor' => 10,
                'character' => 'Marianne',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 8,
                'actor' => 11,
                'character' => 'Héloïse',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 9,
                'actor' => 12,
                'character' => 'Therese Belivet',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 9,
                'actor' => 13,
                'character' => 'Carol Aird',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 10,
                'actor' => 14,
                'character' => 'Alex DeLarge',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 11,
                'actor' => 15,
                'character' => 'Ripley',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 11,
                'actor' => 16,
                'character' => 'Kane',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 12,
                'actor' => 17,
                'character' => 'Antoine Denis',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 12,
                'actor' => 16,
                'character' => 'Olga Denis',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 12,
                'actor' => 16,
                'character' => 'Xan',                        
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('writers')->insert([
            [
                'name' => 'Pedro Almodóvar',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('25 september 1949')),
                'image' => 'pedro_almodovar.jpg',
                'description' => 'Pedro Almodóvar Caballero es un director, guionista y productor de cine español. Fundó la productora de cine española El Deseo S.A. con su hermano menor Agustín Almodóvar, quien ha producido casi todas las películas de Pedro. Fue elegido Miembro Honorario Extranjero de la Academia Estadounidense de las Artes y las Ciencias en 2001.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Mário "Fradique" Bastos',
                'country' => 2,
                'birthdate' => date('Y-m-d H:i:s', strtotime('1986')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ery Claver',
                'country' => 2,
                'birthdate' => date('Y-m-d H:i:s', strtotime('1986')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Paul Schrader',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('22 july 1946')),
                'image' => 'paul_schrader.jpg',
                'description' => 'Paul Joseph Schrader es un guionista y director de cine estadounidense. Su hermano es el también guionista y director Leonard Schrader, con quien ha colaborado en los guiones de Mishima y Blue Collar. Está casado desde el año 1983 con la actriz Mary Beth Hurt, con quien tiene dos hijos, Molly y Sam',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Martin Scorsese',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('17 november 1942')),
                'image' => 'martin_scorsese.jpg',
                'description' => 'Martin Charles Scorsese (nacido el 17 de noviembre de 1942) es un director de cine, productor, guionista y actor estadounidense. Una de las principales figuras de la era del Nuevo Hollywood, es ampliamente considerado como uno de los directores más grandes e influyentes de la historia del cine. El cuerpo de trabajo de Scorsese explora temas como la identidad italoamericana, los conceptos católicos de culpa y redención, la fe, el machismo, el nihilismo, el crimen y el sectarismo.',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Nicholas Pileggi',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('22 february 1933')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Luis García Berlanga',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('12 june 1921')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Rafael Azcona',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('24 october 1926')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ennio Flaiano',
                'country' => 4,
                'birthdate' => date('Y-m-d H:i:s', strtotime('5 march 1910')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Akira Kurosawa',
                'country' => 5,
                'birthdate' => date('Y-m-d H:i:s', strtotime('23 march 1910')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ryūzō Kikushima',
                'country' => 5,
                'birthdate' => date('Y-m-d H:i:s', strtotime('28 january 1914')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Sergio Corbucci',
                'country' => 4,
                'birthdate' => date('Y-m-d H:i:s', strtotime('6 december 1926')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Bruno Corbucci',
                'country' => 4,
                'birthdate' => date('Y-m-d H:i:s', strtotime('23 october 1931')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Céline Sciamma',
                'country' => 6,
                'birthdate' => date('Y-m-d H:i:s', strtotime('12 november 1980')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Phyllis Nagy',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('7 november 1962')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Stanley Kubrick',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('26 july 1928')),
                'image' => 'stanley_kubrick.jpg',
                'description' => 'Stanley Kubrick fue un director de cine, guionista, productor y fotógrafo estadounidense nacionalizado británico. Considerado por muchos como uno de los cineastas más influyentes del siglo XX, destacó tanto por su precisión técnica como por la notable estilización y la profunda carga simbólica de sus películas.​',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Dan O.Bannon',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('30 september 1946')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ronald Shusett',
                'country' => 3,
                'birthdate' => date('Y-m-d H:i:s', strtotime('28 june 1935')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Rodrigo Sorogoyen',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('16 september 1981')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Isabel Peña',
                'country' => 1,
                'birthdate' => date('Y-m-d H:i:s', strtotime('1987')),
                'image' => null,
                'description' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);
        
        DB::table('writing_teams')->insert([
            [
                'film' => 1,
                'writer' => 1,                           
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 2,
                'writer' => 2,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 2,
                'writer' => 3,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 3,
                'writer' => 4,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 4,
                'writer' => 5,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 4,
                'writer' => 6,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 5,
                'writer' => 7,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 5,
                'writer' => 8,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 5,
                'writer' => 9,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 6,
                'writer' => 10,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 6,
                'writer' => 11,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 7,
                'writer' => 12,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 7,
                'writer' => 13,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 8,
                'writer' => 14,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 9,
                'writer' => 15,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 10,
                'writer' => 16,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 11,
                'writer' => 17,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 11,
                'writer' => 18,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 12,
                'writer' => 19,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 12,
                'writer' => 20,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('genres')->insert([
            [
                'name' => 'Drama',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Acción',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Comedia',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Western',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Romance',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Ciencia ficción',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'name' => 'Thiller',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        DB::table('films_genres')->insert([
            [
                'film' => 1,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => 2,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 3,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 4,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 5,
                'genre' => 3,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 6,
                'genre' => 2,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 7,
                'genre' => 4,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 7,
                'genre' => 2,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 8,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 8,
                'genre' => 5,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 9,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 9,
                'genre' => 5,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 10,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 11,
                'genre' => 6,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 12,
                'genre' => 1,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [   
                'film' => 12,
                'genre' => 7,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
        ]);

        $user = User::create([
            'name' => 'Álvaro',
            'email' => 'alvarocc89@gmail.com',
            'password' => Hash::make('12345'),
            'bio' => 'Usuario de prueba',
            'type' => true,
        ]);

        DB::table('reviews')->insert([
            [
                'film' => '1',
                'content' => 'es una película con una trama interesante y compleja que te hace reflexionar sobre temas como la soledad, la comunicación y las relaciones humanas. La película cuenta la historia de dos hombres que se conocen en un hospital mientras cuidan a sus respectivas parejas en coma. A medida que se desarrolla la trama, se exploran temas profundos y emocionales que te dejan pensando incluso después de que termina la película.

                El director, Pedro Almodóvar, logra crear una atmósfera única que te hace sentir como si estuvieras dentro de la película. Los personajes están bien construidos y las actuaciones son excelentes, especialmente la de Javier Cámara, quien interpreta al personaje de Benigno.
                
                Sin embargo, aunque la película es interesante, a veces puede resultar un poco lenta y confusa. Además, algunos de los temas que se exploran pueden resultar incómodos o perturbadores para algunos espectadores.',
                'score' => 3.5,
                'rating' => 0,
                'user' => $user->id,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'film' => '8',
                'content' => 'Obra maestra del cine francés. La película es hermosa tanto visualmente como emocionalmente. La dirección de Céline Sciamma es excepcional, capturando la belleza del paisaje y la época en la que se desarrolla la historia. Las actuaciones de Noémie Merlant y Adèle Haenel son simplemente impresionantes, logrando transmitir la emoción y la tensión de la historia de una manera muy realista. aborda temas como la libertad, el amor y la creatividad, de una manera sutil y profunda. Te hace reflexionar sobre la complejidad de las relaciones humanas y la importancia de la libertad individual.' ,
                'score' => 4.5,
                'rating' => 0,
                'user' => null,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
           
        ]);
        DB::table('comments')->insert([
            [
                'review' => '1',
                'content' => 'Muy interesante tu aportación, Aunque puede resultar un poco incómoda en algunos momentos, en general, es una película que merece la pena ver.',
                'rating' => 0,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
            [
                'review' => '2',
                'content' => 'Sinceramente, no estoy de acuerdo con la crítica anterior sobre "Retrato de una mujer en llamas". Para mí, esta película fue una experiencia larga y aburrida. Sí, es cierto que la dirección de Céline Sciamma es impresionante, y la fotografía y la ambientación son hermosas, pero la trama en sí me pareció lenta y predecible.',
                'rating' => 0,
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ],
           
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('countries')->delete();
        DB::table('directors')->delete();
        DB::table('writers')->delete();
        DB::table('films')->delete();
        DB::table('actors')->delete();
        DB::table('casts')->delete();
        DB::table('filmographies')->delete();
        DB::table('writing_teams')->delete();
        DB::table('reviews')->delete();
        DB::table('genres')->delete();
        DB::table('films_genres')->delete();
        DB::table('comments')->delete();
    }
};
